sudo: required
dist: trusty
#if: tag IS present

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 8.4

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb
      - devscripts
      - fakeroot
      - debhelper
      - automake
      - autotools-dev
      - pkg-config
      - git
      - ca-certificates
      - rpm
      - zip
      - snapd
      - bash

install:
  - nvm install 8.4
  - npm install -g yarn
  - yarn install
  - sudo snap install docker
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  #- if [ -n "$TRAVIS_TAG" ]; then ; fi
  - sudo bash -c "snapcraft() { docker run -v $(pwd):/my-snap snapcore/snapcraft sh -c 'apt update && cd /my-snap && snapcraft $1'; } && yarn run publish"
